[build-options]
  observabilityIncluded = true

[package]
  distribution = "2201.3.1"
  export = ["sample_greeting_service"]
  icon = "docs/icon.png"
  keywords = ["Kind/Sample","Type/Service","Category/Service","Internal/http"]
  name = "sample_greeting_service"
  org = "isurupiyarathnarucji"
  version = "3.1.1"

